package egresscontract

import (
	"fmt"
	"strings"
)

const DecisionHeader = "X-OpenLinker-Egress-Decision"
const HealthPath = "/.well-known/openlinker-egress-health"
const HealthDecision = "healthy"

func TypeScriptSource() string {
	return fmt.Sprintf(
		`// Code generated by go generate ./packages/browser-runtime/egressgateway; DO NOT EDIT.

export const EGRESS_DECISION_HEADER = %q;
export const EGRESS_HEALTH_PATH = %q;
export const EGRESS_HEALTH_DECISION = %q;
`,
		strings.ToLower(DecisionHeader),
		HealthPath,
		HealthDecision,
	)
}
