// Code generated by scripts/generate-codex-rpc.mjs; DO NOT EDIT.
// Stable Codex 0.153.0; schema SHA-256 b06d446edec86cd612537c8826ed4a8abdaeafe8424fdebe5cddd43dd26730ff
package codexrpc

import "encoding/json"

const ProtocolVersion = "0.153.0"

type AbsolutePathBuf string

type AgentMessageDelivery string

type AgentPath string

type AppSummary struct {
	Category    *string `json:"category,omitempty"`
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
	InstallUrl  *string `json:"installUrl,omitempty"`
	Name        string  `json:"name"`
}

type ApprovalsReviewer string

type AskForApproval = json.RawMessage

type AsyncUserInputQuestion struct {
	Options []string `json:"options,omitempty"`
	Title   string   `json:"title"`
}

type ByteRange struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type ClientInfo struct {
	Name    string  `json:"name"`
	Title   *string `json:"title,omitempty"`
	Version string  `json:"version"`
}

type CodexErrorInfo = json.RawMessage

type CollabAgentState struct {
	Message *string           `json:"message,omitempty"`
	Status  CollabAgentStatus `json:"status"`
}

type CollabAgentStatus string

type CollabAgentTool string

type CollabAgentToolCallStatus string

type CommandAction = json.RawMessage

type CommandExecutionSource string

type CommandExecutionStatus string

type DynamicToolCallOutputContentItem = json.RawMessage

type DynamicToolCallStatus string

type ErrorNotification struct {
	Error     TurnError `json:"error"`
	ThreadID  string    `json:"threadId"`
	TurnID    string    `json:"turnId"`
	WillRetry bool      `json:"willRetry"`
}

type FileUpdateChange struct {
	Diff string          `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string          `json:"path"`
}

type FunctionCallOutputBody = json.RawMessage

type FunctionCallOutputContentItem = json.RawMessage

type GitInfo struct {
	Branch    *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type HookPromptFragment struct {
	HookRunID string `json:"hookRunId"`
	Text      string `json:"text"`
}

type ImageDetail string

type ImageGenerationFailure = json.RawMessage

type InitializeCapabilities struct {
	ExperimentalApi                *bool                      `json:"experimentalApi,omitempty"`
	Extensions                     map[string]json.RawMessage `json:"extensions,omitempty"`
	McpServerOpenaiFormElicitation *bool                      `json:"mcpServerOpenaiFormElicitation,omitempty"`
	OptOutNotificationMethods      []string                   `json:"optOutNotificationMethods,omitempty"`
	RequestAttestation             *bool                      `json:"requestAttestation,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo   ClientInfo              `json:"clientInfo"`
}

type InitializeResponse struct {
	CodexHome      json.RawMessage `json:"codexHome"`
	PlatformFamily string          `json:"platformFamily"`
	PlatformOs     string          `json:"platformOs"`
	UserAgent      string          `json:"userAgent"`
}

type ItemCompletedNotification struct {
	CompletedAtMs int64      `json:"completedAtMs"`
	Item          ThreadItem `json:"item"`
	ThreadID      string     `json:"threadId"`
	TurnID        string     `json:"turnId"`
}

type ItemStartedNotification struct {
	Item        ThreadItem `json:"item"`
	StartedAtMs int64      `json:"startedAtMs"`
	ThreadID    string     `json:"threadId"`
	TurnID      string     `json:"turnId"`
}

type LegacyAppPathString string

type McpToolCallAppContext struct {
	ActionName  *string `json:"actionName,omitempty"`
	AppName     *string `json:"appName,omitempty"`
	ConnectorID string  `json:"connectorId"`
	LinkID      *string `json:"linkId,omitempty"`
	ResourceUri *string `json:"resourceUri,omitempty"`
}

type McpToolCallError struct {
	Message string `json:"message"`
}

type McpToolCallResult struct {
	Meta              json.RawMessage   `json:"_meta,omitempty"`
	Content           []json.RawMessage `json:"content"`
	StructuredContent json.RawMessage   `json:"structuredContent,omitempty"`
}

type McpToolCallStatus string

type MemoryCitation struct {
	Entries   []MemoryCitationEntry `json:"entries"`
	ThreadIDs []string              `json:"threadIds"`
}

type MemoryCitationEntry struct {
	LineEnd   int64  `json:"lineEnd"`
	LineStart int64  `json:"lineStart"`
	Note      string `json:"note"`
	Path      string `json:"path"`
}

type MessagePhase string

type MisalignmentErrorDetails struct {
	DetailedExplanation *string            `json:"detailedExplanation,omitempty"`
	ErrorType           *string            `json:"errorType,omitempty"`
	Steer               *MisalignmentSteer `json:"steer,omitempty"`
}

type MisalignmentSteer struct {
	Message string `json:"message"`
}

type NetworkAccess string

type NonSteerableTurnKind string

type PatchApplyStatus string

type PatchChangeKind = json.RawMessage

type Personality string

type PluginAuthPolicy string

type PluginInstallParams struct {
	InstallAttemptID      *string          `json:"installAttemptId,omitempty"`
	MarketplacePath       *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	PluginName            string           `json:"pluginName"`
	RemoteMarketplaceName *string          `json:"remoteMarketplaceName,omitempty"`
}

type PluginInstallResponse struct {
	AppsNeedingAuth []AppSummary     `json:"appsNeedingAuth"`
	AuthPolicy      PluginAuthPolicy `json:"authPolicy"`
}

type ReasoningEffort string

type ReasoningSummary string

type SandboxMode string

type SandboxPolicy = json.RawMessage

type SessionSource = json.RawMessage

type SubAgentActivityKind string

type SubAgentSource = json.RawMessage

type TextElement struct {
	ByteRange   json.RawMessage `json:"byteRange"`
	Placeholder *string         `json:"placeholder,omitempty"`
}

type Thread struct {
	AgentNickname    *string          `json:"agentNickname,omitempty"`
	AgentRole        *string          `json:"agentRole,omitempty"`
	CliVersion       string           `json:"cliVersion"`
	CreatedAt        int64            `json:"createdAt"`
	Cwd              json.RawMessage  `json:"cwd"`
	Ephemeral        bool             `json:"ephemeral"`
	ForkedFromID     *string          `json:"forkedFromId,omitempty"`
	GitInfo          *GitInfo         `json:"gitInfo,omitempty"`
	HistoryMode      json.RawMessage  `json:"historyMode,omitempty"`
	ID               string           `json:"id"`
	Model            *string          `json:"model,omitempty"`
	ModelProvider    string           `json:"modelProvider"`
	Name             *string          `json:"name,omitempty"`
	ParentThreadID   *string          `json:"parentThreadId,omitempty"`
	Path             *string          `json:"path,omitempty"`
	Preview          string           `json:"preview"`
	ProjectID        *string          `json:"projectId,omitempty"`
	ReasoningEffort  *ReasoningEffort `json:"reasoningEffort,omitempty"`
	RecencyAt        *int64           `json:"recencyAt,omitempty"`
	Section          *ThreadSection   `json:"section,omitempty"`
	SectionEnteredAt *int64           `json:"sectionEnteredAt,omitempty"`
	SessionID        string           `json:"sessionId"`
	Source           json.RawMessage  `json:"source"`
	Status           json.RawMessage  `json:"status"`
	ThreadSource     *ThreadSource    `json:"threadSource,omitempty"`
	Turns            []Turn           `json:"turns"`
	UpdatedAt        int64            `json:"updatedAt"`
}

type ThreadActiveFlag string

type ThreadHistoryMode string

type ThreadId string

type ThreadItem struct {
	Action                *WebSearchAction                   `json:"action,omitempty"`
	AgentPath             *string                            `json:"agentPath,omitempty"`
	AgentThreadID         *string                            `json:"agentThreadId,omitempty"`
	AgentsStates          map[string]CollabAgentState        `json:"agentsStates,omitempty"`
	AggregatedOutput      *string                            `json:"aggregatedOutput,omitempty"`
	AppContext            *McpToolCallAppContext             `json:"appContext,omitempty"`
	Arguments             json.RawMessage                    `json:"arguments,omitempty"`
	Changes               []FileUpdateChange                 `json:"changes,omitempty"`
	ClientID              *string                            `json:"clientId,omitempty"`
	Command               *string                            `json:"command,omitempty"`
	CommandActions        []CommandAction                    `json:"commandActions,omitempty"`
	Content               json.RawMessage                    `json:"content,omitempty"`
	ContentItems          []DynamicToolCallOutputContentItem `json:"contentItems,omitempty"`
	Cwd                   json.RawMessage                    `json:"cwd,omitempty"`
	Delivery              *AgentMessageDelivery              `json:"delivery,omitempty"`
	DurationMs            *int64                             `json:"durationMs,omitempty"`
	Error                 *McpToolCallError                  `json:"error,omitempty"`
	ExitCode              *int64                             `json:"exitCode,omitempty"`
	Failure               *ImageGenerationFailure            `json:"failure,omitempty"`
	Fragments             []HookPromptFragment               `json:"fragments,omitempty"`
	ID                    *string                            `json:"id,omitempty"`
	Kind                  *SubAgentActivityKind              `json:"kind,omitempty"`
	McpAppResourceUri     *string                            `json:"mcpAppResourceUri,omitempty"`
	MemoryCitation        *MemoryCitation                    `json:"memoryCitation,omitempty"`
	Model                 *string                            `json:"model,omitempty"`
	Name                  *string                            `json:"name,omitempty"`
	Namespace             *string                            `json:"namespace,omitempty"`
	Output                *FunctionCallOutputBody            `json:"output,omitempty"`
	Path                  *LegacyAppPathString               `json:"path,omitempty"`
	Phase                 *MessagePhase                      `json:"phase,omitempty"`
	PluginID              *string                            `json:"pluginId,omitempty"`
	ProcessID             *string                            `json:"processId,omitempty"`
	Prompt                *string                            `json:"prompt,omitempty"`
	Query                 *string                            `json:"query,omitempty"`
	Questions             []AsyncUserInputQuestion           `json:"questions,omitempty"`
	ReadOnlyHint          *bool                              `json:"readOnlyHint,omitempty"`
	ReasoningEffort       *ReasoningEffort                   `json:"reasoningEffort,omitempty"`
	ReceiverThreadIDs     []string                           `json:"receiverThreadIds,omitempty"`
	Result                json.RawMessage                    `json:"result,omitempty"`
	Results               []json.RawMessage                  `json:"results,omitempty"`
	Review                *string                            `json:"review,omitempty"`
	RevisedPrompt         *string                            `json:"revisedPrompt,omitempty"`
	SavedPath             *AbsolutePathBuf                   `json:"savedPath,omitempty"`
	ScriptPath            *string                            `json:"scriptPath,omitempty"`
	SenderThreadID        *string                            `json:"senderThreadId,omitempty"`
	Server                *string                            `json:"server,omitempty"`
	Source                json.RawMessage                    `json:"source,omitempty"`
	Status                json.RawMessage                    `json:"status,omitempty"`
	Success               *bool                              `json:"success,omitempty"`
	Summary               []string                           `json:"summary,omitempty"`
	Text                  *string                            `json:"text,omitempty"`
	Tool                  json.RawMessage                    `json:"tool,omitempty"`
	TransparentBackground *bool                              `json:"transparentBackground,omitempty"`
	Type                  string                             `json:"type"`
}

type ThreadResumeParams struct {
	ApprovalPolicy        *AskForApproval            `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer         `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string                    `json:"baseInstructions,omitempty"`
	Config                map[string]json.RawMessage `json:"config,omitempty"`
	Cwd                   *string                    `json:"cwd,omitempty"`
	DeveloperInstructions *string                    `json:"developerInstructions,omitempty"`
	ExcludeTurns          *bool                      `json:"excludeTurns,omitempty"`
	Model                 *string                    `json:"model,omitempty"`
	ModelProvider         *string                    `json:"modelProvider,omitempty"`
	Personality           *Personality               `json:"personality,omitempty"`
	Sandbox               *SandboxMode               `json:"sandbox,omitempty"`
	ServiceTier           *string                    `json:"serviceTier,omitempty"`
	ThreadID              string                     `json:"threadId"`
}

type ThreadResumeResponse struct {
	ApprovalPolicy       AskForApproval        `json:"approvalPolicy"`
	ApprovalsReviewer    json.RawMessage       `json:"approvalsReviewer"`
	Cwd                  AbsolutePathBuf       `json:"cwd"`
	InstructionSources   []LegacyAppPathString `json:"instructionSources,omitempty"`
	ItemsBackwardsCursor *string               `json:"itemsBackwardsCursor,omitempty"`
	Model                string                `json:"model"`
	ModelProvider        string                `json:"modelProvider"`
	ReasoningEffort      *ReasoningEffort      `json:"reasoningEffort,omitempty"`
	Sandbox              json.RawMessage       `json:"sandbox"`
	ServiceTier          *string               `json:"serviceTier,omitempty"`
	Thread               Thread                `json:"thread"`
	TurnsBackwardsCursor *string               `json:"turnsBackwardsCursor,omitempty"`
}

type ThreadSection struct {
	Appearance *ThreadSectionAppearance `json:"appearance,omitempty"`
	ID         string                   `json:"id"`
	Name       string                   `json:"name"`
}

type ThreadSectionAppearance struct {
	Color *string `json:"color,omitempty"`
	Icon  *string `json:"icon,omitempty"`
}

type ThreadSource string

type ThreadStartParams struct {
	ApprovalPolicy        *AskForApproval            `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer         `json:"approvalsReviewer,omitempty"`
	BaseInstructions      *string                    `json:"baseInstructions,omitempty"`
	Config                map[string]json.RawMessage `json:"config,omitempty"`
	Cwd                   *string                    `json:"cwd,omitempty"`
	DeveloperInstructions *string                    `json:"developerInstructions,omitempty"`
	Ephemeral             *bool                      `json:"ephemeral,omitempty"`
	Model                 *string                    `json:"model,omitempty"`
	ModelProvider         *string                    `json:"modelProvider,omitempty"`
	Personality           *Personality               `json:"personality,omitempty"`
	Sandbox               *SandboxMode               `json:"sandbox,omitempty"`
	ServiceName           *string                    `json:"serviceName,omitempty"`
	ServiceTier           *string                    `json:"serviceTier,omitempty"`
	SessionStartSource    *ThreadStartSource         `json:"sessionStartSource,omitempty"`
	ThreadSource          *ThreadSource              `json:"threadSource,omitempty"`
}

type ThreadStartResponse struct {
	ApprovalPolicy     AskForApproval        `json:"approvalPolicy"`
	ApprovalsReviewer  json.RawMessage       `json:"approvalsReviewer"`
	Cwd                AbsolutePathBuf       `json:"cwd"`
	InstructionSources []LegacyAppPathString `json:"instructionSources,omitempty"`
	Model              string                `json:"model"`
	ModelProvider      string                `json:"modelProvider"`
	ReasoningEffort    *ReasoningEffort      `json:"reasoningEffort,omitempty"`
	Sandbox            json.RawMessage       `json:"sandbox"`
	ServiceTier        *string               `json:"serviceTier,omitempty"`
	Thread             Thread                `json:"thread"`
}

type ThreadStartSource string

type ThreadStatus = json.RawMessage

type Turn struct {
	CompletedAt *int64          `json:"completedAt,omitempty"`
	DurationMs  *int64          `json:"durationMs,omitempty"`
	Error       *TurnError      `json:"error,omitempty"`
	ID          string          `json:"id"`
	Items       []ThreadItem    `json:"items"`
	ItemsView   json.RawMessage `json:"itemsView,omitempty"`
	StartedAt   *int64          `json:"startedAt,omitempty"`
	Status      TurnStatus      `json:"status"`
}

type TurnCompletedNotification struct {
	ThreadID string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnError struct {
	AdditionalDetails *string                   `json:"additionalDetails,omitempty"`
	CodexErrorInfo    *CodexErrorInfo           `json:"codexErrorInfo,omitempty"`
	Message           string                    `json:"message"`
	Misalignment      *MisalignmentErrorDetails `json:"misalignment,omitempty"`
}

type TurnInterruptParams struct {
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type TurnInterruptResponse map[string]json.RawMessage

type TurnItemsView string

type TurnStartParams struct {
	ApprovalPolicy      *AskForApproval    `json:"approvalPolicy,omitempty"`
	ApprovalsReviewer   *ApprovalsReviewer `json:"approvalsReviewer,omitempty"`
	ClientUserMessageID *string            `json:"clientUserMessageId,omitempty"`
	Cwd                 *string            `json:"cwd,omitempty"`
	Effort              *ReasoningEffort   `json:"effort,omitempty"`
	Input               []UserInput        `json:"input"`
	Model               *string            `json:"model,omitempty"`
	OutputSchema        json.RawMessage    `json:"outputSchema,omitempty"`
	Personality         *Personality       `json:"personality,omitempty"`
	SandboxPolicy       *SandboxPolicy     `json:"sandboxPolicy,omitempty"`
	ServiceTier         *string            `json:"serviceTier,omitempty"`
	ServiceTierForTurn  *string            `json:"serviceTierForTurn,omitempty"`
	Summary             *ReasoningSummary  `json:"summary,omitempty"`
	ThreadID            string             `json:"threadId"`
	ToolOutput          *TurnToolOutput    `json:"toolOutput,omitempty"`
	TurnTrigger         *string            `json:"turnTrigger,omitempty"`
}

type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

type TurnStartedNotification struct {
	ThreadID string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnStatus string

type TurnToolOutput struct {
	Name      string                 `json:"name"`
	Namespace *string                `json:"namespace,omitempty"`
	Output    FunctionCallOutputBody `json:"output"`
}

type UserInput struct {
	Detail       *ImageDetail  `json:"detail,omitempty"`
	Name         *string       `json:"name,omitempty"`
	Path         *string       `json:"path,omitempty"`
	Text         *string       `json:"text,omitempty"`
	TextElements []TextElement `json:"text_elements,omitempty"`
	Type         string        `json:"type"`
	Url          *string       `json:"url,omitempty"`
}

type WebSearchAction = json.RawMessage
