package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/OpenLinker-ai/openlinker-plugin/packages/browser-runtime/browserprotocol/internal/browsercontract"
)

func main() {
	target := filepath.Join(
		"..",
		"browser-engine",
		"src",
		"browser-contract.generated.ts",
	)
	content := fmt.Sprintf(
		`// Code generated by go generate ./packages/browser-runtime/browserprotocol; DO NOT EDIT.

export const BROWSER_VIEWPORT_WIDTH = %d;
export const BROWSER_VIEWPORT_HEIGHT = %d;
export const BROWSER_STATE_RETENTION_MS = %d;
`,
		browsercontract.ViewportWidth,
		browsercontract.ViewportHeight,
		browsercontract.StateRetention.Milliseconds(),
	)
	if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
		panic(err)
	}
}
