package browserprotocol

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/OpenLinker-ai/openlinker-plugin/packages/browser-runtime/browserprotocol/internal/browsercontract"
)

type browserProtocolContractFixtures struct {
	PublicURLs []struct {
		Value    string `json:"value"`
		Accepted bool   `json:"accepted"`
	} `json:"public_urls"`
	Coordinates []struct {
		X        int  `json:"x"`
		Y        int  `json:"y"`
		Accepted bool `json:"accepted"`
	} `json:"coordinates"`
}

func TestGeneratedBrowserContractIsCurrent(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(
		"..",
		"browser-engine",
		"src",
		"browser-contract.generated.ts",
	))
	if err != nil {
		t.Fatal(err)
	}
	want := fmt.Sprintf(
		`// Code generated by go generate ./packages/browser-runtime/browserprotocol; DO NOT EDIT.

export const BROWSER_VIEWPORT_WIDTH = %d;
export const BROWSER_VIEWPORT_HEIGHT = %d;
export const BROWSER_STATE_RETENTION_MS = %d;
`,
		browsercontract.ViewportWidth,
		browsercontract.ViewportHeight,
		browsercontract.StateRetention.Milliseconds(),
	)
	if string(raw) != want {
		t.Fatal("Browser engine contract is stale; run go generate ./packages/browser-runtime/browserprotocol")
	}
}

func TestGoBrowserProtocolMatchesSharedContractFixtures(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(
		"..",
		"browser-engine",
		"contract-fixtures.json",
	))
	if err != nil {
		t.Fatal(err)
	}
	var fixtures browserProtocolContractFixtures
	if err := json.Unmarshal(raw, &fixtures); err != nil {
		t.Fatal(err)
	}
	for _, fixture := range fixtures.PublicURLs {
		failure := (Action{Kind: ActionNavigate, URL: fixture.Value}).Validate()
		if got := failure == nil; got != fixture.Accepted {
			t.Errorf(
				"navigate %q accepted = %t, want %t (failure=%v)",
				fixture.Value,
				got,
				fixture.Accepted,
				failure,
			)
		}
	}
	for _, fixture := range fixtures.Coordinates {
		x, y := fixture.X, fixture.Y
		failure := (Action{Kind: ActionClick, X: &x, Y: &y}).Validate()
		if got := failure == nil; got != fixture.Accepted {
			t.Errorf(
				"coordinate (%d,%d) accepted = %t, want %t (failure=%v)",
				x,
				y,
				got,
				fixture.Accepted,
				failure,
			)
		}
	}
}
