// Code generated by go generate ./packages/browser-runtime/egressgateway; DO NOT EDIT.

export const EGRESS_DECISION_HEADER = "x-openlinker-egress-decision";
export const EGRESS_HEALTH_PATH = "/.well-known/openlinker-egress-health";
export const EGRESS_HEALTH_DECISION = "healthy";
